# 1. Data Loading and exploration

## 1. Loading Data

In [2]:
import numpy as np
import pandas as pd

In [5]:
customers = pd.read_csv('wk8-customers.csv')

In [6]:
customers

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,NaN,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,Texas,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,NaN,555.444.9876,135 Madison St,Austin,TX,NaN,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,NaN,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,North Carolina,28202,NaN
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,Washington,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,Oregon,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,NaN
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,Maryland,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,2021-01-28
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [8]:
inventory = pd.read_csv('wk8-inventory.csv')

In [9]:
inventory

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0
...,...,...,...,...,...,...
70,71,15,5,0,2022-10-16,10.0
71,72,15,10,22,2022-09-25,8.0
72,73,15,15,29,2022-11-22,10.0
73,74,15,20,0,2022-10-01,15.0
74,75,15,25,36,NaN,10.0

In [10]:
products = pd.read_csv('wk8-products.csv')

In [11]:
products

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20
5,6,Levi's Slim Jeans,clothing,Pants,Levi's,59.99,31.00,0.90
6,7,KitchenAid Stand Mixer,Home & Kitchen,Kitchen Appliances,KitchenAid,349.99,245.00,10.00
7,8,Cuisinart Coffee Maker,home & kitchen,Kitchen Appliances,Cuisinart,99.99,55.00,3.50
8,9,IKEA Malm Dresser,Home and Kitchen,Furniture,IKEA,179.99,85.00,NaN
9,10,Penguin Classics Collection,Books,Fiction,Penguin,49.99,27.50,2.00
10,11,The North Face Jacket,Sports & Outdoors,Jackets,The North Face,199.99,110.00,1.30
11,12,Nike Running Shoes,sports & outdoors,Shoes,Nike,129.99,65.00,0.70
12,13,LEGO Star Wars Set,Toys,Building Toys,LEGO,89.99,45.00,1.50
13,14,L'Oreal Revitalift Cream,Beauty,Skincare,L'Oreal,19.99,8.00,0.30
14,15,Apple MacBook Pro,Electronics,Laptops,Apple,-1599.99,1100.00,3.50
15,16,Bose QuietComfort 45,Electronics,Headphones,Bose,329.99,495.00,0.50
16,17,Hershey's Chocolate Assortment,Grocery,Snacks,Hershey's,15.99,7.00,1.00
17,18,Adidas Track Pants,Clothing,Pants,Adidas,45.99,23.00,0.60
18,19,Kindle Paperwhite,ELECTRONICS,E-Readers,Amazon,139.99,80.00,0.40
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
20,21,Outdoor Gas Grill,Home & Kitchen,Outdoor,Weber,299.99,165.00,25.00
21,22,Calvin Klein Men's Shirt,Apparel,Shirts,Calvin Klein,39.99,20.00,NaN
22,23,Coleman Camping Tent,Sports and Outdoors,Camping,Coleman,149.99,75.00,8.50
23,24,Mattel Barbie Dreamhouse,Toys,Dolls,Mattel,199.99,99.00,12.00
24,25,Neutrogena Face Wash,beauty,Skincare,Neutrogena,9.99,4.00,0.35
25,26,General Mills Cereal,Food,Breakfast,General Mills,4.99,1.80,0.90
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50
27,28,HP Wireless Printer,electronics,Printers,HP,129.99,85.00,15.00
28,29,Zara Maxi Dress,Clothing,Dresses,Zara,79.99,32.00,0.50
29,30,Columbia Winter Parka,Sports & Outdoors,Jackets,Columbia,249.99,150.00,3.20

In [12]:
sales = pd.read_csv('wk8-sales.csv')

In [13]:
sales

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC
5,6,2022-02-01,2.0,17,1,1,899.99,Visa
6,7,2022-02-03,7.0,25,12,2,259.98,PayPal
7,8,2022-02-05,9.0,14,20,1,599.99,Apple Pay
8,9,2022-02-08,10.0,6,4,1,1299.99,Debit
9,10,2022-02-10,3.0,19,9,1,179.99,Cash
10,11,2022-02-15,NaN,22,2,1,799.99,Credit Card
11,12,2022-02-19,5.0,7,18,3,137.97,DC
12,13,2022-02-22,8.0,10,23,2,299.98,cash
13,14,2022-03-01,12.0,2,11,1,199.99,Credit Card
14,15,2022-03-05,15.0,16,6,2,120.48,Debit Card
15,16,2022-03-10,1.0,27,13,3,269.97,paypal
16,17,2022-03-15,3.0,9,27,1,499.99,ApplePay
17,18,2022-03-20,6.0,4,17,4,61.96,Cash
18,19,2022-03-25,9.0,23,21,1,299.99,Credit Card
19,20,2022-04-01,11.0,28,25,2,19.98,CREDIT CARD
20,21,2022-04-05,13.0,12,8,1,99.99,Debit Card
21,22,2022-04-10,2.0,5,19,1,139.99,PP
22,23,2022-04-15,4.0,15,14,3,59.97,Cash
23,24,2022-04-20,7.0,21,22,2,79.98,Credit
24,25,2022-04-25,10.0,3,16,1,329.99,GooglePay
25,26,2022-05-01,14.0,8,24,1,199.99,Credit Card
26,27,2022-05-05,1.0,18,28,1,129.99,debit card
27,28,2022-05-10,5.0,26,1,1,900.50,Cash
28,29,2022-05-15,9.0,11,7,1,349.99,PayPal
29,30,2022-05-20,3.0,24,9,2,359.98,Debit Card
30,31,NaN,2.0,13,4,1,1299.99,Credit Card
31,32,2022-06-01,6.0,29,26,5,24.95,Cash
32,33,2022-06-05,8.0,1,5,3,67.47,NaN
33,34,2022-06-10,11.0,6,22,1,39.99,Debit Card
34,35,2022-06-15,4.0,17,29,2,159.98,Credit Card
35,36,2022-06-20,7.0,9,10,2,98.98,Cash
36,37,2022-06-25,12.0,27,3,1,349.99,PayPal
37,38,2022-07-01,15.0,20,11,1,199.99,google pay
38,39,2022-07-05,3.0,16,30,2,499.98,Credit Card
39,40,2022-07-10,1.0,5,3,1,349.99,CASH

In [14]:
stores = pd.read_csv('wk8-stores.csv')

In [15]:
stores

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30
5,6,Philadelphia Center,987 Market St,Philadelphia,PA,19103,Northeast,22000.0,2009-09-12
6,7,San Antonio Mall,741 River Walk,San Antonio,TX,78205,Southwest,35000.0,2012-04-22
7,8,San Diego Plaza,852 Pacific Hwy,San Diego,CA,92101,West,27500.0,2006-07-18
8,9,Dallas Galleria,963 Lone Star Blvd,Dallas,TX,75201-5555,Southwest,42000.0,NaN
9,10,Boston Outlet,159 Freedom Rd,Boston,Massachusetts,02108,Northeast,16500.0,2014-10-09
10,11,Seattle City Center,753 Rainy St,Seattle,WA,98101,West,29000.0,2011-02-14
11,12,Denver Mountain Mall,951 Mile High Dr,Denver,CO,80202,West,31500.0,2015-08-27
12,13,Miami Beach Plaza,357 Ocean Dr,Miami,FL,33139,Southeast,24000.0,2016-12-03
13,14,Minneapolis Galleria,852 Lake St,Minneapolis,MN,55401,Midwest,NaN,2013-05-11
14,15,Atlanta Outlet,456 Peachtree St,Atlanta,Georgia,30303,Southeast,20000.0,2018-09-25

## 2. Exploratory Analysis

### Summary Statistics

In [17]:
inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [18]:
products.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [19]:
sales.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

### Check for null values

In [31]:
stores.isnull().sum()

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [32]:
products.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

In [33]:
sales.isnull().sum()

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [34]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

In [35]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

### Display Data types

In [38]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        31 non-null     int64
 1   first_name         31 non-null     str
 2   last_name          31 non-null     str
 3   email              28 non-null     str
 4   phone              29 non-null     str
 5   address            31 non-null     str
 6   city               31 non-null     str
 7   state              31 non-null     str
 8   zip_code           30 non-null     str
 9   registration_date  28 non-null     str
dtypes: int64(1), str(9)
memory usage: 2.6 KB

In [39]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       75 non-null     int64
 1   store_id           75 non-null     int64
 2   product_id         75 non-null     int64
 3   quantity_in_stock  75 non-null     int64
 4   last_restock_date  66 non-null     str
 5   reorder_level      69 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 3.6 KB

In [40]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     int64
 1   product_name  30 non-null     str
 2   category      30 non-null     str
 3   subcategory   30 non-null     str
 4   brand         30 non-null     str
 5   price         30 non-null     float64
 6   cost          30 non-null     float64
 7   weight        28 non-null     float64
dtypes: float64(3), int64(1), str(4)
memory usage: 2.0 KB

In [41]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         40 non-null     int64
 1   date            39 non-null     str
 2   store_id        39 non-null     float64
 3   customer_id     40 non-null     int64
 4   product_id      40 non-null     int64
 5   quantity        40 non-null     int64
 6   total           40 non-null     float64
 7   payment_method  39 non-null     str
dtypes: float64(2), int64(4), str(2)
memory usage: 2.6 KB

In [42]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      15 non-null     int64
 1   store_name    15 non-null     str
 2   address       15 non-null     str
 3   city          15 non-null     str
 4   state         15 non-null     str
 5   zip_code      15 non-null     str
 6   region        15 non-null     str
 7   size_sqft     13 non-null     float64
 8   opening_date  14 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 1.2 KB

### Basic Information Retrieval

In [56]:
products[['product_id', 'product_name']]\
    .drop_duplicates

products['product_name'].unique
# 29 unique values

<bound method Series.unique of 0                    Apple iPhone 13
1                 Samsung Galaxy S21
2                    Sony WH-1000XM4
3                        Dell XPS 13
4                   Nike Classic Tee
5                  Levi's Slim Jeans
6             KitchenAid Stand Mixer
7             Cuisinart Coffee Maker
8                  IKEA Malm Dresser
9        Penguin Classics Collection
10             The North Face Jacket
11                Nike Running Shoes
12                LEGO Star Wars Set
13          L'Oreal Revitalift Cream
14                 Apple MacBook Pro
15              Bose QuietComfort 45
16    Hershey's Chocolate Assortment
17                Adidas Track Pants
18                 Kindle Paperwhite
19                  Dyson V11 Vacuum
20                 Outdoor Gas Grill
21          Calvin Klein Men's Shirt
22              Coleman Camping Tent
23          Mattel Barbie Dreamhouse
24              Neutrogena Face Wash
25              General Mills Cereal
26                Sony PlayStation 5
27               HP Wireless Printer
28                   Zara Maxi Dress
29             Columbia Winter Parka
Name: product_name, dtype: str>

In [57]:
products.sort_values(by='price', ascending=False).head(5)

,product_id,product_name,category,subcategory,brand,price,cost,weight
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50

In [60]:
stores.sort_values(by='size_sqft', ascending=False).head(1)

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10

In [61]:
customers['state'].value_counts()

state
TX                4
CA                3
NY                2
California        1
IL                1
AZ                1
PA                1
Texas             1
FL                1
OH                1
North Carolina    1
IN                1
Washington        1
CO                1
MA                1
Oregon            1
NV                1
MI                1
TN                1
Maryland          1
MD                1
KY                1
WI                1
NM                1
MO                1
Name: count, dtype: int64

# 2. Data Cleaning

## Handling Missing Values

In [81]:
customers.isnull

<bound method DataFrame.isnull of     customer_id   first_name  last_name                   email  \
0             1        James      Smith   james.smith@gmail.com
1             2         Mary    Johnson                     NaN
2             3         John   Williams     jwilliams@yahoo.com
3             4     Patricia      Brown      pbrown@hotmail.com
4             5       Robert      Jones      rjones23@gmail.com
5             6     Jennifer     Miller     jmiller@outlook.com
6             7      Michael      Davis        mdavis@gmail.com
7             8        Linda     Garcia       lgarcia@yahoo.com
8             9      William  Rodriguez  wrodriguez@hotmail.com
9            10    Elizabeth     Wilson       ewilson@gmail.com
10           11        David   Martinez     dmartinez@yahoo.com
11           12      Barbara   Anderson                     NaN
12           13      Richard     Taylor     rtaylor@outlook.com
13           14        Susan     Thomas     sthomas45@gmail.com
14           15       Joseph  Hernandez    jhernandez@yahoo.com
15           16      Jessica      Moore      jmoore@hotmail.com
16           17       Thomas     Martin       tmartin@gmail.com
17           18        Sarah    Jackson      sjackson@yahoo.com
18           19      Charles   Thompson   cthompson@outlook.com
19           20        Karen      White      kwhite88@gmail.com
20           21  Christopher      Lopez        clopez@yahoo.com
21           22        Nancy        Lee        nlee@hotmail.com
22           23       Daniel   Gonzalez     dgonzalez@gmail.com
23           24     Margaret     Harris       mharris@yahoo.com
24           25      Matthew      Clark      mclark@outlook.com
25           26        Betty      Lewis   betty.lewis@gmail.com
26           26        Betty      Lewis      blewis23@gmail.com
27           27       Steven   Robinson     srobinson@yahoo.com
28           28      Dorothy     Walker     dwalker@hotmail.com
29           29      Anthony      Perez                     NaN
30           30         Lisa       Hall         lhall@gmail.com

             phone                  address           city           state  \
0     555-123-4567              123 Main St       New York              NY
1     212.555.6789             456 Park Ave       New York              NY
2   (555) 987-6543             789 Broadway    Los Angeles      California
3       5551234567               321 Elm St        Chicago              IL
4     555-987-3456              555 Pine St        Houston              TX
5              NaN             898 Cedar Dr        Phoenix              AZ
6     555.432.7654            742 Maple Ave   Philadelphia              PA
7     555 876 2345               953 Oak Ln    San Antonio           Texas
8       5558889999      159 Washington Blvd      San Diego              CA
9   (555) 333-2211           753 Lincoln Rd         Dallas              TX
10    555-111-3333        246 Jefferson Ave       San Jose              CA
11    555.444.9876           135 Madison St         Austin              TX
12      5552223333             864 Adams Ct   Jacksonville              FL
13             NaN            579 Monroe Pl     Fort Worth              TX
14    555-777-8888           951 Jackson Dr       Columbus              OH
15    555.666.1234             357 Tyler St      Charlotte  North Carolina
16  (555) 444-5678             159 Polk Ave  San Francisco              CA
17      5557890123          753 Harrison Rd   Indianapolis              IN
18    555-321-6547         951 Van Buren St        Seattle      Washington
19    555.789.4561          357 Fillmore Dr         Denver              CO
20    555 456 7890           159 Pierce Ave         Boston              MA
21      5559876543           753 Hayes Blvd       Portland          Oregon
22  (555) 123-7890             951 Grant St      Las Vegas              NV
23    555-321-6789           357 Sherman Rd        Detroit              MI
24    555.654.9870          159 Sheridan Dr      Nashville              TN
25      5551597532       753 MacArthur Blvd      Baltimore        Maryland
26    555 159 7532  753 MacArthur Boulevard      Baltimore              MD
27    555-951-7532            951 Hooker St     Louisville              KY
28      5553579514          357 Halsted Ave      Milwaukee              WI
29    555.753.9512           159 Ashland Dr    Albuquerque              NM
30  (555) 951-7530            753 Morgan St    Kansas City              MO

      zip_code registration_date
0        10001        2021-03-15
1        10022        2020-11-02
2   90001-1234        2021-05-20
3        60601               NaN
4        77002        2020-09-12
5        85001        2021-02-28
6        19103        2021-01-17
7        78205        2020-10-05
8        92101        2021-06-30
9        75201        2020-08-22
10       95113        2021-04-09
11         NaN        2020-12-27
12       32202        2021-07-14
13       76102        2020-07-18
14       43215        2021-01-03
15       28202               NaN
16       94102        2020-10-19
17       46204        2021-03-01
18       98101        2020-09-05
19       80202        2021-05-12
20       02108        2020-11-30
21       97201        2021-02-14
22       89101        2020-08-08
23       48226        2021-04-25
24       37201               NaN
25       21202        2020-07-01
26       21202        2020-07-01
27       40202        2021-06-17
28       53202        2020-09-30
29       87102        2021-01-28
30       64101        2020-10-15  >

In [101]:
customers['registration_date'] = customers['registration_date'].bfill()
customers['registration_date']

0     2021-03-15
1     2020-11-02
2     2021-05-20
3     2021-05-20
4     2020-09-12
5     2021-02-28
6     2021-01-17
7     2020-10-05
8     2021-06-30
9     2020-08-22
10    2021-04-09
11    2020-12-27
12    2021-07-14
13    2020-07-18
14    2021-01-03
15    2021-01-03
16    2020-10-19
17    2021-03-01
18    2020-09-05
19    2021-05-12
20    2020-11-30
21    2021-02-14
22    2020-08-08
23    2021-04-25
24    2021-04-25
25    2020-07-01
26    2020-07-01
27    2021-06-17
28    2020-09-30
29    2021-01-28
30    2020-10-15
Name: registration_date, dtype: str

In [80]:
inventory.isnull

<bound method DataFrame.isnull of     inventory_id  store_id  product_id  quantity_in_stock last_restock_date  \
0              1         1           1                 25        2022-10-15
1              2         1           5                 42        2022-11-02
2              3         1          10                 18        2022-09-30
3              4         1          15                  5        2022-10-20
4              5         1          20                 12               NaN
..           ...       ...         ...                ...               ...
70            71        15           5                  0        2022-10-16
71            72        15          10                 22        2022-09-25
72            73        15          15                 29        2022-11-22
73            74        15          20                  0        2022-10-01
74            75        15          25                 36               NaN

    reorder_level
0            10.0
1            15.0
2             8.0
3            10.0
4            15.0
..            ...
70           10.0
71            8.0
72           10.0
73           15.0
74           10.0

[75 rows x 6 columns]>

In [92]:
products.isnull

<bound method DataFrame.isnull of     product_id                    product_name             category  \
0            1                 Apple iPhone 13          Electronics
1            2              Samsung Galaxy S21          electronics
2            3                 Sony WH-1000XM4          ELECTRONICS
3            4                     Dell XPS 13          Electronics
4            5                Nike Classic Tee             Clothing
5            6               Levi's Slim Jeans             clothing
6            7          KitchenAid Stand Mixer       Home & Kitchen
7            8          Cuisinart Coffee Maker       home & kitchen
8            9               IKEA Malm Dresser     Home and Kitchen
9           10     Penguin Classics Collection                Books
10          11           The North Face Jacket    Sports & Outdoors
11          12              Nike Running Shoes    sports & outdoors
12          13              LEGO Star Wars Set                 Toys
13          14        L'Oreal Revitalift Cream               Beauty
14          15               Apple MacBook Pro          Electronics
15          16            Bose QuietComfort 45          Electronics
16          17  Hershey's Chocolate Assortment              Grocery
17          18              Adidas Track Pants             Clothing
18          19               Kindle Paperwhite          ELECTRONICS
19          20                Dyson V11 Vacuum       HOME & KITCHEN
20          21               Outdoor Gas Grill       Home & Kitchen
21          22        Calvin Klein Men's Shirt              Apparel
22          23            Coleman Camping Tent  Sports and Outdoors
23          24        Mattel Barbie Dreamhouse                 Toys
24          25            Neutrogena Face Wash               beauty
25          26            General Mills Cereal                 Food
26          27              Sony PlayStation 5          Electronics
27          28             HP Wireless Printer          electronics
28          29                 Zara Maxi Dress             Clothing
29          30           Columbia Winter Parka    Sports & Outdoors

           subcategory           brand    price     cost  weight
0          Smartphones           Apple   899.99   649.99    0.45
1          Smartphones         Samsung   799.99   539.99    0.50
2           Headphones            Sony   349.99   210.00    0.60
3              Laptops            Dell  1299.99   899.99    2.80
4               Shirts            Nike    24.99    12.50    0.20
5                Pants          Levi's    59.99    31.00    0.90
6   Kitchen Appliances      KitchenAid   349.99   245.00   10.00
7   Kitchen Appliances       Cuisinart    99.99    55.00    3.50
8            Furniture            IKEA   179.99    85.00     NaN
9              Fiction         Penguin    49.99    27.50    2.00
10             Jackets  The North Face   199.99   110.00    1.30
11               Shoes            Nike   129.99    65.00    0.70
12       Building Toys            LEGO    89.99    45.00    1.50
13            Skincare         L'Oreal    19.99     8.00    0.30
14             Laptops           Apple -1599.99  1100.00    3.50
15          Headphones            Bose   329.99   495.00    0.50
16              Snacks       Hershey's    15.99     7.00    1.00
17               Pants          Adidas    45.99    23.00    0.60
18           E-Readers          Amazon   139.99    80.00    0.40
19          Appliances           Dyson   599.99   375.00    6.70
20             Outdoor           Weber   299.99   165.00   25.00
21              Shirts    Calvin Klein    39.99    20.00     NaN
22             Camping         Coleman   149.99    75.00    8.50
23               Dolls          Mattel   199.99    99.00   12.00
24            Skincare      Neutrogena     9.99     4.00    0.35
25           Breakfast   General Mills     4.99     1.80    0.90
26              Gaming            Sony   499.99   399.00    4.50
27            Printers              HP   129.99    85.00   15.00
28             Dresses            Zara    79.99    32.00    0.50
29             Jackets        Columbia   249.99   150.00    3.20  >

In [79]:
sales.isnull

<bound method DataFrame.isnull of     sale_id        date  store_id  customer_id  product_id  quantity    total  \
0         1  2022-01-15       3.0           12           5         2    49.98
1         2  2022-01-16       1.0            5          10         1    49.99
2         3  2022-01-18       2.0            8           3         1   349.99
3         4  2022-01-20       4.0           20           7         1   349.99
4         5  2022-01-22       5.0            3          15         1  1599.99
5         6  2022-02-01       2.0           17           1         1   899.99
6         7  2022-02-03       7.0           25          12         2   259.98
7         8  2022-02-05       9.0           14          20         1   599.99
8         9  2022-02-08      10.0            6           4         1  1299.99
9        10  2022-02-10       3.0           19           9         1   179.99
10       11  2022-02-15       NaN           22           2         1   799.99
11       12  2022-02-19       5.0            7          18         3   137.97
12       13  2022-02-22       8.0           10          23         2   299.98
13       14  2022-03-01      12.0            2          11         1   199.99
14       15  2022-03-05      15.0           16           6         2   120.48
15       16  2022-03-10       1.0           27          13         3   269.97
16       17  2022-03-15       3.0            9          27         1   499.99
17       18  2022-03-20       6.0            4          17         4    61.96
18       19  2022-03-25       9.0           23          21         1   299.99
19       20  2022-04-01      11.0           28          25         2    19.98
20       21  2022-04-05      13.0           12           8         1    99.99
21       22  2022-04-10       2.0            5          19         1   139.99
22       23  2022-04-15       4.0           15          14         3    59.97
23       24  2022-04-20       7.0           21          22         2    79.98
24       25  2022-04-25      10.0            3          16         1   329.99
25       26  2022-05-01      14.0            8          24         1   199.99
26       27  2022-05-05       1.0           18          28         1   129.99
27       28  2022-05-10       5.0           26           1         1   900.50
28       29  2022-05-15       9.0           11           7         1   349.99
29       30  2022-05-20       3.0           24           9         2   359.98
30       31         NaN       2.0           13           4         1  1299.99
31       32  2022-06-01       6.0           29          26         5    24.95
32       33  2022-06-05       8.0            1           5         3    67.47
33       34  2022-06-10      11.0            6          22         1    39.99
34       35  2022-06-15       4.0           17          29         2   159.98
35       36  2022-06-20       7.0            9          10         2    98.98
36       37  2022-06-25      12.0           27           3         1   349.99
37       38  2022-07-01      15.0           20          11         1   199.99
38       39  2022-07-05       3.0           16          30         2   499.98
39       40  2022-07-10       1.0            5           3         1   349.99

   payment_method
0     Credit Card
1     credit card
2      DEBIT CARD
3            Cash
4              CC
5            Visa
6          PayPal
7       Apple Pay
8           Debit
9            Cash
10    Credit Card
11             DC
12           cash
13    Credit Card
14     Debit Card
15         paypal
16       ApplePay
17           Cash
18    Credit Card
19    CREDIT CARD
20     Debit Card
21             PP
22           Cash
23         Credit
24      GooglePay
25    Credit Card
26     debit card
27           Cash
28         PayPal
29     Debit Card
30    Credit Card
31           Cash
32            NaN
33     Debit Card
34    Credit Card
35           Cash
36         PayPal
37     google pay
38    Credit Card
39           CASH  >

In [77]:
stores.isnull

<bound method DataFrame.isnull of     store_id            store_name             address          city  \
0          1           City Center     123 Retail Blvd      New York
1          2       Mall of Chicago    456 Shopping Ave       Chicago
2          3     Los Angeles Plaza     789 Commerce St   Los Angeles
3          4      Houston Galleria         321 Main St       Houston
4          5        Phoenix Outlet       654 Desert Rd       Phoenix
5          6   Philadelphia Center       987 Market St  Philadelphia
6          7      San Antonio Mall      741 River Walk   San Antonio
7          8       San Diego Plaza     852 Pacific Hwy     San Diego
8          9       Dallas Galleria  963 Lone Star Blvd        Dallas
9         10         Boston Outlet      159 Freedom Rd        Boston
10        11   Seattle City Center        753 Rainy St       Seattle
11        12  Denver Mountain Mall    951 Mile High Dr        Denver
12        13     Miami Beach Plaza        357 Ocean Dr         Miami
13        14  Minneapolis Galleria         852 Lake St   Minneapolis
14        15        Atlanta Outlet    456 Peachtree St       Atlanta

            state    zip_code     region  size_sqft opening_date
0              NY       10001  Northeast    32500.0   2005-05-20
1              IL       60611    Midwest    45000.0   2007-08-15
2              CA       90001       West    55000.0   2004-03-10
3           Texas       77002  Southwest        NaN   2008-11-05
4              AZ       85001  Southwest    18500.0   2010-06-30
5              PA       19103  Northeast    22000.0   2009-09-12
6              TX       78205  Southwest    35000.0   2012-04-22
7              CA       92101       West    27500.0   2006-07-18
8              TX  75201-5555  Southwest    42000.0          NaN
9   Massachusetts       02108  Northeast    16500.0   2014-10-09
10             WA       98101       West    29000.0   2011-02-14
11             CO       80202       West    31500.0   2015-08-27
12             FL       33139  Southeast    24000.0   2016-12-03
13             MN       55401    Midwest        NaN   2013-05-11
14        Georgia       30303  Southeast    20000.0   2018-09-25  >

In [110]:
stores['opening_date'].bfill()

0     2005-05-20
1     2007-08-15
2     2004-03-10
3     2008-11-05
4     2010-06-30
5     2009-09-12
6     2012-04-22
7     2006-07-18
8     2014-10-09
9     2014-10-09
10    2011-02-14
11    2015-08-27
12    2016-12-03
13    2013-05-11
14    2018-09-25
Name: opening_date, dtype: str

### Replacing numeric values with mean

In [82]:
sales['store_id'].fillna(sales['store_id'].mean())

0      3.000000
1      1.000000
2      2.000000
3      4.000000
4      5.000000
5      2.000000
6      7.000000
7      9.000000
8     10.000000
9      3.000000
10     6.487179
11     5.000000
12     8.000000
13    12.000000
14    15.000000
15     1.000000
16     3.000000
17     6.000000
18     9.000000
19    11.000000
20    13.000000
21     2.000000
22     4.000000
23     7.000000
24    10.000000
25    14.000000
26     1.000000
27     5.000000
28     9.000000
29     3.000000
30     2.000000
31     6.000000
32     8.000000
33    11.000000
34     4.000000
35     7.000000
36    12.000000
37    15.000000
38     3.000000
39     1.000000
Name: store_id, dtype: float64

In [83]:
products['weight'].fillna(products['weight'].mean())

0      0.450000
1      0.500000
2      0.600000
3      2.800000
4      0.200000
5      0.900000
6     10.000000
7      3.500000
8      3.835714
9      2.000000
10     1.300000
11     0.700000
12     1.500000
13     0.300000
14     3.500000
15     0.500000
16     1.000000
17     0.600000
18     0.400000
19     6.700000
20    25.000000
21     3.835714
22     8.500000
23    12.000000
24     0.350000
25     0.900000
26     4.500000
27    15.000000
28     0.500000
29     3.200000
Name: weight, dtype: float64

In [90]:
stores['size_sqft'].fillna(stores['size_sqft'].mean())

0     32500.000000
1     45000.000000
2     55000.000000
3     30653.846154
4     18500.000000
5     22000.000000
6     35000.000000
7     27500.000000
8     42000.000000
9     16500.000000
10    29000.000000
11    31500.000000
12    24000.000000
13    30653.846154
14    20000.000000
Name: size_sqft, dtype: float64

### Replacing categorical columns

In [96]:
customers['phone'] = customers['phone'].fillna(customers['phone'].mode()[0])
customers['phone']

0       555-123-4567
1       212.555.6789
2     (555) 987-6543
3         5551234567
4       555-987-3456
5     (555) 123-7890
6       555.432.7654
7       555 876 2345
8         5558889999
9     (555) 333-2211
10      555-111-3333
11      555.444.9876
12        5552223333
13    (555) 123-7890
14      555-777-8888
15      555.666.1234
16    (555) 444-5678
17        5557890123
18      555-321-6547
19      555.789.4561
20      555 456 7890
21        5559876543
22    (555) 123-7890
23      555-321-6789
24      555.654.9870
25        5551597532
26      555 159 7532
27      555-951-7532
28        5553579514
29      555.753.9512
30    (555) 951-7530
Name: phone, dtype: str

In [107]:
sales['payment_method'] = sales['payment_method'].fillna(sales['payment_method'].mode()[0])
sales['payment_method']

0     Credit Card
1     credit card
2      DEBIT CARD
3            Cash
4              CC
5            Visa
6          PayPal
7       Apple Pay
8           Debit
9            Cash
10    Credit Card
11             DC
12           cash
13    Credit Card
14     Debit Card
15         paypal
16       ApplePay
17           Cash
18    Credit Card
19    CREDIT CARD
20     Debit Card
21             PP
22           Cash
23         Credit
24      GooglePay
25    Credit Card
26     debit card
27           Cash
28         PayPal
29     Debit Card
30    Credit Card
31           Cash
32    Credit Card
33     Debit Card
34    Credit Card
35           Cash
36         PayPal
37     google pay
38    Credit Card
39           CASH
Name: payment_method, dtype: str

In [89]:
customers['zip_code'] = customers['zip_code'].fillna(customers['zip_code'].mode()[0])
customers['zip_code']

0          10001
1          10022
2     90001-1234
3          60601
4          77002
5          85001
6          19103
7          78205
8          92101
9          75201
10         95113
11         21202
12         32202
13         76102
14         43215
15         28202
16         94102
17         46204
18         98101
19         80202
20         02108
21         97201
22         89101
23         48226
24         37201
25         21202
26         21202
27         40202
28         53202
29         87102
30         64101
Name: zip_code, dtype: str

### Date columns with missing values

In [101]:
customers['registration_date'] = customers['registration_date'].bfill()
customers['registration_date']

0     2021-03-15
1     2020-11-02
2     2021-05-20
3     2021-05-20
4     2020-09-12
5     2021-02-28
6     2021-01-17
7     2020-10-05
8     2021-06-30
9     2020-08-22
10    2021-04-09
11    2020-12-27
12    2021-07-14
13    2020-07-18
14    2021-01-03
15    2021-01-03
16    2020-10-19
17    2021-03-01
18    2020-09-05
19    2021-05-12
20    2020-11-30
21    2021-02-14
22    2020-08-08
23    2021-04-25
24    2021-04-25
25    2020-07-01
26    2020-07-01
27    2021-06-17
28    2020-09-30
29    2021-01-28
30    2020-10-15
Name: registration_date, dtype: str

In [109]:
inventory['last_restock_date'].ffill()

0     2022-10-15
1     2022-11-02
2     2022-09-30
3     2022-10-20
4     2022-10-20
         ...
70    2022-10-16
71    2022-09-25
72    2022-11-22
73    2022-10-01
74    2022-10-01
Name: last_restock_date, Length: 75, dtype: str

In [110]:
stores['opening_date'].bfill()

0     2005-05-20
1     2007-08-15
2     2004-03-10
3     2008-11-05
4     2010-06-30
5     2009-09-12
6     2012-04-22
7     2006-07-18
8     2014-10-09
9     2014-10-09
10    2011-02-14
11    2015-08-27
12    2016-12-03
13    2013-05-11
14    2018-09-25
Name: opening_date, dtype: str

In [103]:
sales['date'] = sales['date'].ffill()
sales['date']

0     2022-01-15
1     2022-01-16
2     2022-01-18
3     2022-01-20
4     2022-01-22
5     2022-02-01
6     2022-02-03
7     2022-02-05
8     2022-02-08
9     2022-02-10
10    2022-02-15
11    2022-02-19
12    2022-02-22
13    2022-03-01
14    2022-03-05
15    2022-03-10
16    2022-03-15
17    2022-03-20
18    2022-03-25
19    2022-04-01
20    2022-04-05
21    2022-04-10
22    2022-04-15
23    2022-04-20
24    2022-04-25
25    2022-05-01
26    2022-05-05
27    2022-05-10
28    2022-05-15
29    2022-05-20
30    2022-05-20
31    2022-06-01
32    2022-06-05
33    2022-06-10
34    2022-06-15
35    2022-06-20
36    2022-06-25
37    2022-07-01
38    2022-07-05
39    2022-07-10
Name: date, dtype: str

# Discussion Questions

1. Pandas cleans data faster, it keeps your originall data in tact, and it has built in cleaning tools

2. I would approach it as if it was not an error. Assume missing values need to be imputed.

3. Missing values and whether or not they are random.

4. use a jupyter notebook, convert your results to a csv file, or assign your resulst to a new variable.

5. It would be appropriate to remove an entire row if the row doesn"t affect your analysis.